### ISSUE TITLE
apn_payload_add_custom_property doesn't work with string values

### ISSUE THREAD

**Issue by mingalevme** [adobkin/php-apn#1]
``` php
apn_payload_add_custom_property($payload, 'test', 56); // works
apn_payload_add_custom_property($payload, 'test', NULL); // works
apn_payload_add_custom_property($payload, 'test', TRUE); // works
apn_payload_add_custom_property($payload, 'test', 'TEST'); // successfully sending, but the devices don't receive the notification
```

Additional Info:
Apple Push Notification Service support enabled
Extension Version                   1.0.0
Version of libcapn                  1.0.0

P.S. There is no docs for apn_payload_add_custom_property: http://libcapn.org/php-apn/doc/html/index.html

**Comment by adobkin** [comment]
It's capn library bug https://github.com/adobkin/libcapn/issues/1
