### ISSUE TITLE
Using it without installing

### ISSUE THREAD

**Issue by yesprasoon** [adobkin/php-apn#8]
Is there any way to use this library / module without installing anything? My company uses a shared hosting server. With my very limited knowledge of server side programming, I understand that it's impossible (or very complicated) to install anything without root access. In that case, how to use php-apn? Can't I just copy all required files, and use require_once or something like that? I had used pushwoosh php script in same way.

**Comment by adobkin** [comment]
No, you must install libcapn library and php-apn extension.
